project:
  type: website

website:
  title: "frank blog"
  navbar:
    title: "frank blog<span class='name_container._8'></span>"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/edenian-prince/blog
format:
  nwpage-html:
    theme: [styles.scss ]
    # page-layout: article
    # grid:
    #   sidebar-width: 1px
    #   body-width: 500px
    #   gutter-width: 1px
    toc: true






