project:
  type: website

website:
  title: "Frank Anthony"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/edenian-prince/blog
format:
  nwpage-html: default




